version: '3'
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./site.conf:/etc/nginx/conf.d/site.conf
      - ./hello.html:/usr/share/nginx/html/index.html
    ports:
      - "8080:80"
    restart: always


